### ISSUE TITLE
Fishhash prebuilt dataset, can it be more fast?

### ISSUE THREAD

**Issue by blackmennewstyle** [iron-fish/fish-hash#14]
Hello beautiful devs,

I have a question regarding the prebuilt dataset, even with 8 threads it makes more than 4 minutes to be generated, is there anyway to improve that process? I think people who will need to generate it with on a 4 threads server will definitely have an hard time.

**Comment by danield9tqh** [comment]
Hey @blackmennewstyle building the dataset is not meant to be done more than once when running a node / miner. Is there a reason you're needing to build it multiple times? One solution I could think of is saving the built dataset to disk and loading it from disk on a restart

**Comment by blackmennewstyle** [comment]
Hello Daniel :)

Thanks for the heads-up and suggestion.
